return {}

-- return {
--   {
--     "nvim-neo-tree/neo-tree.nvim",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--       "MunifTanjim/nui.nvim",
--       -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
--     },
--     opts = {
--       filesystem = {
--         window = {
--           mappings = {
--             ["D"] = "show_diff",
--           },
--         },
--         commands = {
--           show_diff = function(state)
--             local node = state.tree:get_node()
--
--             local is_file = node.type == "file"
--             if not is_file then
--               vim.notify("Diff only for files", vim.log.levels.ERROR)
--               return
--             end
--
--             local cc = require("neo-tree.sources.common.commands")
--             cc.open(state, function()
--               -- do nothing for dirs
--             end)
--
--             -- diffview.nvim
--             vim.cmd([[DiffviewOpen -- %]])
--           end,
--         },
--       },
--     },
--   },
-- }
